### ISSUE TITLE
Feedback thread for experimental spell checker service

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#1064]
[v0.3.13-beta05](https://github.com/florisboard/florisboard/releases/tag/v0.3.13-beta05) adds an experimental spell checker service. This issue thread serves as a collection of feedback for this feature and will be used to improve the spell checker until it releases on the stable channel with v0.3.13. Feel free to comment down below, any feedback from suggestions to bug / crash reports for the spell checker is welcome!

Wiki entry for help with using the spell checker: https://github.com/florisboard/florisboard/wiki/System-spell-checker-service

Revision 1: #1069 (beta06)
Revision 2: #1082 (beta07)
Revision 3: #1082 (beta08)
Revision 4: #1172 (beta10)

### Known issues / Suggested improvements [will be extended dynamically]

- [x] Dictionaries with languages containing Cyrillic characters (Greek, Bulgarian etc) fail to load (especially those from Firefox and Free Office), possibly encoding issue (Fixed in #1069)
- [x] The APK size is too high, try optimizing (especially ICU data) (Fixed in #1082)
- [x] Language is fixed per session, interferes with "Use keyboard subtypes" when switching the subtype while a session is active
- [x] Czech XPI extension from Mozilla does not conform to expected format causing a crash when importing, fix importer script (Fixed in #1069)
- [x] Bulgarian Mozilla extension license file uses different name, add fix (Fixed in #1069)
- [x] Auto-capitalization pref is incorrectly labeled as "Spell checker" (Fixed in #1069)
- [x] FreeOffice link leads to nowhere when used on German devices (make link statically linked to `en`) (Fixed in #1069)
- [ ] Best correction match should show in Smartbar (inline spellchecking)

...

**Comment by kocjs** [comment]
Thanks for florisbord.


I use the freeoffice dictionaries, using subtypes in the settings. The spell checker works quite well, wrong words are underlined in German and English as intended. However if i switch to an other subtype, the dictionary does not switch with it. I have to close the app (Telegram), to the dictionary switched too.

**Comment by vojta-horanek** [comment]
Crash when opening a czech dictionary from Mozzila.

#### Environment information
- FlorisBoard Version: 0.3.13-beta05 (48)
- Device: Samsung SM-A505FN
- Android: 11 (cn=R sdk=30)

#### Features enabled
```kt
smartbar = true
suggestions = false
suggestions_clipboard = true
suggestions_next_word = true
glide = true
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1626184897059.stacktrace</summary>

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	... 1 more
Caused by: java.io.FileNotFoundException: /data/user/0/dev.patrickgold.florisboard.beta/cache/__temp000__ime_spelling_import_new_dict/cs_CZ/cs_CZ.aff: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
	at dev.patrickgold.florisboard.ime.spelling.SpellingManager.prepareImport-gIAlu-s(SpellingManager.kt:213)
	at dev.patrickgold.florisboard.settings.spelling.ImportDictionaryFragment.importDict$lambda-5(ImportDictionaryFragment.kt:51)
	at dev.patrickgold.florisboard.settings.spelling.ImportDictionaryFragment.lambda$B1W-grqL87TnSfoLsCdIZzvpqNI(Unknown Source:0)
	at dev.patrickgold.florisboard.settings.spelling.-$$Lambda$ImportDictionaryFragment$B1W-grqL87TnSfoLsCdIZzvpqNI.onActivityResult(Unknown Source:4)
	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
	at androidx.fragment.app.Fragment.performStart(Fragment.java:3013)
	at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:586)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1636)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3112)
	at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3063)
	at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:482)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
	at android.app.Activity.performStart(Activity.java:8222)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3818)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8512)
	... 3 more
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8373)
	at libcore.io.IoBridge.open(IoBridge.java:478)
	... 36 more

```
</details>

**Comment by patrickgold** [comment]
> I use the freeoffice dictionaries, using subtypes in the settings. The spell checker works quite well, wrong words are underlined in German and English as intended. However if i switch to an other subtype, the dictionary does not switch with it. I have to close the app (Telegram), to have the dictionary switched too.

Thanks for the feedback. This is an issue known to me, although I don't know how to fix it, as the active language is determined at a spell checker session startup, and this is most of the time at app start (or per text field sometimes). I will add it to the above task list, will see if I can work around it.

**Comment by patrickgold** [comment]
> Crash when opening a czech dictionary from Mozzila.

Thanks for reporting this! It seems like some dictionaries of Mozilla are structured slightly differently and this is enough to get FlorisBoard to crash. Will place it on the task list!

**Comment by StoyanDimitrov** [comment]
LG-H850 with LOS 18.1. The spellcheck doesn't show any signs of live. It ether does not override the system one (although I set up the system to use FlorisBoard's) and shows the system's dropdown and stuff (I believe this is fixed with restart of the host app) or doesn't underline the misspelled words at all. Restarted the host app (Telegram). Tested with:
* https://addons.mozilla.org/firefox/addon/bulgarian-dictionary/ - installed as archive
* https://addons.mozilla.org/firefox/addon/us-english-dictionary/ - installed as separate .aff + .dic files

Noticed a strange behaviour when typing Bulgarian. After the first 2-3 keypresses in an application (when typing for the first time) the keyboard disappears and reappears moment later - no crash. Probably should prepare a log. Could it be encoding related? BG spellcheck dicts use `CP1251` (`windows-1251`).

Nitpick: You may want to take a look at BG spellchecking dictionary archive. There are several license files but none of them recognized as such in `Verify import files` section of the `Import new dictionary` screen.

**Comment by Glitchy-Tozier** [comment]
The freeoffice-link doesn't lead anywhere.
![Screenshot_20210714-120441_Firefox Nightly.jpg](https://user-images.githubusercontent.com/59611881/125604219-20982468-01dd-4119-9452-8f1eeb13c099.jpg)

**Comment by Glitchy-Tozier** [comment]
So... is this intended? The word-suggestions show up in the text instead of in the suggestions-bar.
![Screenshot_20210714-122203_GitHub.jpg](https://user-images.githubusercontent.com/59611881/125606827-36800b06-1313-4b7f-b511-0eb55107b448.jpg)

**Comment by patrickgold** [comment]
> Noticed a strange behaviour when typing Bulgarian. After the first 2-3 keypresses in an application (when typing for the first time) the keyboard disappears and reappears moment later - no crash.

This behavior indicates a crash in the native shared library, which does not produce crash reports (literally impossible due to the nature of compiled objects being executed).

> Could it be encoding related? BG spellcheck dicts use CP1251 (windows-1251)

Nuspell uses ICU to convert between different codepages and encodings, though if the dictionary encoding is misinterpreted as UTF-8, then things won't work. As Greek dictionaries from Mozilla show the same behavior, I suspect that the encoding of Cyrillic characters could be the issue.

> Nitpick: You may want to take a look at BG spellchecking dictionary archive. There are several license files but none of them recognized as such in Verify import files section of the Import new dictionary screen.

Probably because there is no definite standard for license file names and the Bulgarian one deviates from the en-US baseline. This is a rather easy fix though, will add it to the task list.

**Comment by patrickgold** [comment]
> The freeoffice-link doesn't lead anywhere.

It does but FreeOffice messes up server-side. I use the locale-independent link (https://www.freeoffice.com/download/dictionaries). This causes FreeOfice's web server to look up what languages your browser supports and redirect you to the appropriate page. For English this is (https://www.freeoffice.com/en/download/dictionaries) and this page also exists. For German it correctly detects `de` as the language code but there is no German download page (would be https://www.freeoffice.com/de/download/dictionaries), thus the 404 error. In this case the English page _should_ be shown.

I used the locale-independent link so users get a translated dictionary page (if available), but it seems FreeOffice does not do this job well. Only fix for this is to statically link to the English download page.

> So... is this intended? The word-suggestions show up in the text instead of in the suggestions-bar.

Currently yes because that's the spell check UI the system provides. I also plan to show the best correction match in the Smartbar but like stated in the wiki this is not yet supported.

**Comment by patrickgold** [comment]
> I only have limited spellcheck-experience but I thought keyboards wouldn't rely on the system to provide corrections.

I never said I use corrections provided by the system - I only use the API from the system to be able to display corrections within the target app's UI. The spell checker framework from the system works like that:

1. An app starts input in a text field (by focusing it etc.)
2. If it wants that the text the user types in gets spell checked, it sets an appropiate flag, else it doesn't
3. If that flag is set, the system attempts to start your selected spell checker (in this case FlorisBoard), if it succeeds requests a session.
4. Within the session, the system then takes the text from the target app and calls a getter method of my spell checker service [`FlorisSpellCheckerService`](https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/FlorisSpellCheckerService.kt). The service class then does the internal job at using the dictionary and checking if it is correct and if it isn't provide corrections (see `onGetSuggestions`).
5. The sentence suggestions get returned back and for each element which is marked as incorrect a red line is rendered in the target app's text field.

**Comment by patrickgold** [comment]
Or to put it in other words: FlorisBoard does **not** want to use the system spell checker, but it aims to **be** the system spell checker. The openness of the Android platform allows for such and FlorisBoard wants to utilize the framework for this by implementing all functionality your default system spell checker is also supporting (this includes inline spelling and corrections in the text field).

**Comment by Glitchy-Tozier** [comment]
> I never said I use corrections provided by the system


> The sentence suggestions get returned back and for each element which is marked as incorrect a red line is rendered in the target app's text field.

What I meant are the red lines. Did you trigger them on purpose? Samsung-keyboard doesn't result in those.
![Screenshot_20210714-174853_GitHub.jpg](https://user-images.githubusercontent.com/59611881/125652278-a1a9f562-a092-4435-9668-989d0e87191b.jpg)

**Comment by patrickgold** [comment]
> What I meant are the red lines. Did you trigger them on purpose? Samsung-keyboard doesn't result in those.

The red lines are words marked as incorrect by the system spell checker, if you have chosen FlorisBoard then yes, FlorisBoard did trigger those.

Afaik Samsung has done some special things in the spell checker area, and the Samsung keyboard does only do spell checking within the keyboard UI (Samsung hates the spell checker framework from core Android, I don't know why). Gboard/Google does both, FlorisBoard currently only in the text field (but will also do both in the future).

**Comment by Glitchy-Tozier** [comment]
I see, in that case I'll do my best to get used to the mid-text lines 🙃

Any idea about the automatic capitalization?

**Comment by patrickgold** [comment]
> Any idea about the automatic capitalization?

Yeah, I fucked up:
![image](https://user-images.githubusercontent.com/19412843/125660621-6cb28ac7-11e7-4739-aed3-5c291b240ef7.png)

The first "Spell checker" list entry leads you to the spell checker preferences (this is correct), the second is the auto capitalization toggle pref (but is labeled as the spell checker). Thus enabling this pref enables auto-capitalization. I don't exactly know what I did there, but I will make sure to fix it haha.

**Comment by Glitchy-Tozier** [comment]
Lol never thought of that 😂

That's reassuring actually, because it means it's not Android/Samsung imposing weird things on us.

**Comment by Glitchy-Tozier** [comment]
@patrickgold If you need a mozilla-crash-log, here you go:

kotlinx.serialization.MissingFieldException: Field 'dictionaries' is required for type with serial name 'dev.patrickgold.florisboard.ime.spelling.SpellingManager.Companion.FirefoxManifestJson', but it was missing

Btw, clicking on the "copy to clipboard"-button only compies a small amout of text.

Here's part of the actual log:

![Screenshot_20210714-204525_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/125676003-326b9bf7-b235-48ea-bb5a-efaae8eb7631.jpg)

**Comment by patrickgold** [comment]
Which Mozilla dictionary did you try? I have to check which weird format they use there, because the dictionaries field is normally a required one.

**Comment by Glitchy-Tozier** [comment]
Whoops, forgot to mention that. I used the most common EN_GB dictionary: https://addons.mozilla.org/de/firefox/addon/english-gb-language-pack/

**Comment by patrickgold** [comment]
Thanks for linking, will try it out later.

Could you try if this link works fine on your phone: https://www.freeoffice.com/en/download/dictionaries . If it does, I will use this link for FreeOffice.

**Comment by Glitchy-Tozier** [comment]
Slightly off-topic but is there a way to have word corrections for multiple languages at once, without switching keyboard languages?

**Comment by Glitchy-Tozier** [comment]
> Could you try if this link works fine on your phone:

Yup, my phone didn't hate this website. :)
(Or the website didn't hate my locale I guess)

![Screenshot_20210714-205231_Firefox Nightly.jpg](https://user-images.githubusercontent.com/59611881/125676831-aef8f1ba-a502-4a2f-9daf-1a496b1f15c8.jpg)

**Comment by Glitchy-Tozier** [comment]
> Thanks for the feedback. This is an issue known to me, although I don't know how to fix it, as the active language is determined at a spell checker session startup, and this is most of the time at app start (or per text field sometimes). I will add it to the above task list, will see if I can work around it.

Maybe this suggestion is completely nonsensical (hey my spellchecker didn't complain, I spelled the word correctly 😁), but couldn't you restart or re-trigger the session upon language switch?

**Comment by patrickgold** [comment]
> (Or the website didn't hate my locale I guess)

More like that :) Thanks for confirming!

> Maybe this suggestion is completely nonsensical (hey my spellchecker didn't complain, I spelled the word correctly grin), but couldn't you restart or re-trigger the session upon language switch?

I wish I could, but the session is managed by the system. I could try hack around it by checking the locale in `onGetSuggestions`every time and dynamically switch out the dictionary, which is a small performance hit though.

**Comment by Glitchy-Tozier** [comment]
What does checking the locale do? (session-wise)

Also, couldn't you re-check the locale upon language-switch? (as an additional onClick-event on the language-switch-button)

**Comment by patrickgold** [comment]
> Also, couldn't you re-check the locale upon language-switch? (as an additional onClick-event on the language-switch-button)

I could register an event listener while the session is active, that's actually not a bad idea! (less though on the onClick but more in the SubtypeManager, but the base idea is still good)

**Comment by Glitchy-Tozier** [comment]
Work your magic, then!  :)

**Comment by patrickgold** [comment]
> What does checking the locale do? (session-wise)

There are two locales:
- The spell checker locale, basically either a valid language code (indicates I must use the system language) or "zz", meaning I use the active subtype locale. Cannot be re-interpreted/checked during a session.
- The subtype language, basically the language displayed on your space bar. Can be rechecked during a session (with the event listener idea).

**Comment by StoyanDimitrov** [comment]
> Nuspell uses ICU to convert between different codepages and encodings, though if the dictionary encoding is misinterpreted as UTF-8, then things won't work. As Greek dictionaries from Mozilla show the same behavior, I suspect that the encoding of Cyrillic characters could be the issue.

Confirmed! Converting the files to UTF-8 and installing them as separate affix and dictionary brought back this useful thing to life.

Unfortunately ICU is not perfect with regards to Cyrillics as other software have troubles with it too.

**Comment by StoyanDimitrov** [comment]
> 
> 
> Whoops, forgot to mention that. I used the most common EN_GB dictionary: https://addons.mozilla.org/de/firefox/addon/english-gb-language-pack/

This is a **language pack** for the browser's UI and not a dictionary.

**Comment by seanlaguna** [comment]
I wanted to use this thread to ask some questions about the future of the spell checker service with respect to suggestions; please tell me if there's a better place to discuss! All of the comments I'll be making are in the context of en-US since that's what I use, and I'm on a Xiaomi Mi 6 (Android 9).

The previous smartbar suggestions (i.e. the ones on stable) contain many spurious words that seem either like uncommon acronyms or things that aren't even actual words, or contractions without apostrophes, etc. I'm not sure where the suggestions are obtained, but it looks like the place those suggestions are obtained contains many non-words or spurious, uncommon words. I know the whole smartbar and suggestions components are being reworked, so I wanted to ask how the suggestions will be computed in the future, if it is intended to be completely different from the old method (I think it probably should be), and what the method and considerations will be in generating the suggestions for a given "word" (space-delimited entry) that the user inputs.

Like many I am coming from SwiftKey and want to move away from it for various reasons (privacy, supporting open-source, better keyboard design, etc). SwiftKey gets a **lot** right when it comes to suggestions though. I think the considerations for suggestions should include, at least, the following:
- from a spell-checker (planned?)
- from a user dictionary (already implemented?)
- based on nearby letters on keyboard, not just spelling (important for good suggestions!)
- respecting Shift and CAPS LOCK
- respecting some other capitalization settings (should words like "I" always be capitalized, should beginning of sentence always be capitalized, etc)
- based on previous word (planned?)
- based on word usage frequency (in combination with above)
- learning from some other user behaviors (preserving privacy, of course)
- setting for auto-correcting with best suggestion (or if the suggestion is above some threshold, via a setting) on space; this one's really important for me, since on SwitfKey I can really just time fast and sloppy and it'll get 95% of the words right through auto-correcting me

I know it's a lot but I think it's possible and will really help FlorisBoard compete with the best predictive keyboards out there (i.e. SwiftKey haha). To be honest, I think spell-checking is a great feature but I really want all the UI to be part of the keyboard app, not inside my other applications with red squiggly lines. The current "add to dictionary" popup has a completely transparent background, and that plus other aspects of it makes it hard to read, and hard to interact with as it overlaps with many other UI elements. I think maybe putting an indicator in the smart bar when the cursor is in a word that isn't in the dictionary, and having the options for how to handle it in the smart bar, could be a good way forward.

I'm interested in possibly helping implement some of this too.

I don't mean to be too critical, I'm still using FlorisBoard in its current state and it's a very promising project, with obviously a lot of hard work put into it! A huge thanks for starting this project and for the work being put into it.

**Comment by Glitchy-Tozier** [comment]
@seanlaguna I think the best place for the more general discussions (those that aren't directly related to the feedback for beta 5) is #325.

I think it's best to move your post there  :)

There you can also read about some of stuff that is planned.

**Comment by patrickgold** [comment]
> The previous smartbar suggestions (i.e. the ones on stable) contain many spurious words that seem either like uncommon acronyms or things that aren't even actual words, or contractions without apostrophes, etc.

Yes, I am aware that the current word suggestions are not the greatest, but at the time they were the solution. I am not entirely sure where I will get the word lists, an idea could be to prepare wordlists from the Hunspell dictionaries and repackage them, so they can be used for suggestion. This would not include a frequency parameter though, but maybe I can solve this by dynamically learning these as the user writes.

> I know it's a lot but I think it's possible and will really help FlorisBoard compete with the best predictive keyboards out there (i.e. SwiftKey haha)

This list is indeed very exhaustive, but we need to get there eventually :) My direct plan for spell checking is to include the best correction match (if there is one) for the current word integrated into the Smartbar (and if "Auto correct" is on it will also be automatically replaced when inputting a non-word character (space, period etc)).

> from a user dictionary (already implemented?)

Already implemented but a bit strict in finding words currently.

> based on nearby letters on keyboard, not just spelling (important for good suggestions!)

I've seen that one in ASK or OpenBoard I think and yes, this could also contribute to better suggestions (although I am not sure how to add this one without a performance decrease).

> respecting Shift and CAPS LOCK
respecting some other capitalization settings (should words like "I" always be capitalized, should beginning of sentence always be capitalized, etc)

This will definitely be added because it is annoying (especially in languages where every noun needs capitalization haha).

> based on previous word (planned?)
based on word usage frequency (in combination with above)
learning from some other user behaviors (preserving privacy, of course)

That's somewhat tied into one feature, namely learning based on the user's input. Will see what I will do, the upmost important thing regardless of what I choose to do here is to make it privacy-respecting and local-only.

> To be honest, I think spell-checking is a great feature but I really want all the UI to be part of the keyboard app, not inside my other applications with red squiggly lines

This is completely subjective, some users coming from desktop really like to see such feature (I do too), others like you want it in the keyboard, some want both, so this will be customizable when everything is implemented of course!

> The current "add to dictionary" popup has a completely transparent background, and that plus other aspects of it makes it hard to read, and hard to interact with as it overlaps with many other UI elements. I think maybe putting an indicator in the smart bar when the cursor is in a word that isn't in the dictionary, and having the options for how to handle it in the smart bar, could be a good way forward.

The add to dictionary dialog is rendered by the system and not by FlorisBoard, so I don't have control how it looks like and if it overlaps weird. I agree though that the Smartbar should provide this option as well, together with the inline spell checking. Will be targeted for the beta07 release.

> I don't mean to be too critical

Being critical is good, because it means that something does not work well (and suggestions are undeniably a mess to say the least), this also helps me to see what I can improve etc. So thank you for your exhaustive feedback :)

**Comment by Glitchy-Tozier** [comment]
> However if i switch to an other subtype, the dictionary does not switch with it. I have to close the app (Telegram), to have the dictionary switched too.

What's weird is that this doesn't happen in every app. In the GitHub-app i can switch language and then just rotate the phone. This resets the spellcheck-language.

In Signal, I have to close and reopen the app to achieve any change.

**Comment by patrickgold** [comment]
> What's weird is that this doesn't happen in every app. In the GitHub-app i can switch language and then just rotate the phone. This resets the spellcheck-language.

Rotating the screen normally causes the entire activity views to be recreated, and with this also the spell checker session. If the session is tied to the activity view model state though (like probably done in Signal), it won't reset until you leave and open Signal again.

**Comment by IdreesM0** [comment]
Excuse me for polluting the otherwise productive forum but I use FBoard as my primary keyboard. Thank you for making the best android keyboard. I was currently looking for getting spell checker on my phone and came accross this issue. Im so excited to see that this is already being worked on. Wish you all the best. And thank you once again!

**Comment by bege10** [comment]
Hello,
currently I am using Multiling Keyboard which uses the AOSP spellchecker. I read this thread and I don't yet understand what FB needs an own spellchecker service for.

**Comment by patrickgold** [comment]
@bege10 Having an own spell checker service means FlorisBoard can provide private inline spell checking on any device. This is especially important for devices running with Google Services, because these most often have the proprietary Google Spell checker as the default and this would be one way for Google to capture some of your text input. Of course, if you are on a de-googled device and use the AOSP spell checker, this might be enough already.

**Comment by bege10** [comment]
> 
> 
> @bege10 Having an own spell checker service means FlorisBoard can provide private inline spell checking on any device. This is especially important for devices running with Google Services, because these most often have the proprietary Google Spell checker as the default and this would be one way for Google to capture some of your text input. Of course, if you are on a de-googled device and use the AOSP spell checker, this might be enough already.

Thank you for the explanation. Now I understand. Indeed, I use a de-googled device.

Will FlorisBoard be able to work with the AOSP spell checker and its user dictionaries?

**Comment by patrickgold** [comment]
> Will FlorisBoard be able to work with the AOSP spell checker and its user dictionaries?

The Android framework is designed that spell checker service is decoupled from the keyboard and thus you can use FlorisBoard and the AOSP spell checker at the same time, Smartbar spell checker corrections will still be available as long as you import a Hunspell dictionary for your language. Note that Smartbar corrections are planned, see above task list.

The system user dictionary is already supported (Settings > Typing > Dictionaries), the spell checker and word suggestions can use it. FlorisBoard additionally provides an internal one if someone does not want other keyboards to access the user dictionary.

**Comment by bege10** [comment]
@patrickgold That sounds very deliberate. I am curious about the development to come.

**Comment by Glitchy-Tozier** [comment]
The spell-checker doesn't seem to like abbreviations. Maybe periods in the spellchecked text are being ignored?

https://user-images.githubusercontent.com/59611881/128131226-3ac5e625-2557-4210-8021-970ea7134ddc.mp4

**Comment by patrickgold** [comment]
That's an interesting topic to bring up. For spell checking, the word separation is currently done by the Android platform, though I have the ability to do this myself I think. The Android framework probably sees a dot as the end of a sentence, rather than parts of a word. Will see if I can come up with a solution.

**Comment by Waelwindows** [comment]
> The word separation is currently done by the Android platform, though I have the ability to do this myself I think.

If possible try to use Android's word segmentation because it should handle CJK languages out of the box which would otherwise be hard to implement on our end.

**Comment by patrickgold** [comment]
Above linked PR #1172 is the last spell check related PR before the stable 0.3.13 release and aims to fix some bugs, as well as address the issue with switching keyboard subtypes during a spell checker session.

Previously it was impossible for the session to recognize a language switch, thus once a text field was opened, switching between subtypes didn't change the spell checker language. Now the session can, with some limitations, detect a language change and react to that:
- Immediately after pressing the subtype switch button in the keyboard UI nothing happens, this can not be changed due to the design of the Android spell check framework though, as no re-check is triggered.
- When inputting any non-word character (symbols like space, dot, comma, question mark, ...), the words are immediately re-checked and after 1-2 secs the words are now marked for the new subtype's language. Subsequent words are also checked in the new subtype's language.
- Inputting a word-character (letter) does not trigger a re-check. Again, I can't do much here and am bound to the Android spell checker framework here. If any symbol follows after a letter, a re-check occurs, thus the new language is the one used for checking the words.

Considering the new logic for detecting a language change in the keyboard subtype works pretty well (besides of the few limitations), I will see the "Use keyboard subtype"-switcher issue as fixed.

Tomorrow I will see if a spell checker Smartbar integration is doable without too much of a hassle, if it is then this will also be included in beta10, else in 0.3.15 probably.

All bug fixes will be present in the 0.3.13-beta10 release on Sunday, as well as in the stable 0.3.13 release at the end of next week (when no critical bugs are reported in-between). Thanks again for everyone in this thread for giving their feedback on spell checking, this helped a lot in identifying issues early on and making this feature great!

**Comment by patrickgold** [comment]
> If possible try to use Android's word segmentation because it should handle CJK languages out of the box which would otherwise be hard to implement on our end.

I've never heard of a public API for such thing, only internal ones. Do you by any chance have a link to the documentation of this feature?

**Comment by Glitchy-Tozier** [comment]
Did something change inside the settings? No text I write seems to get spell-checked anymore.

`nKaoaoa ajsjsbw wjw So this is weird.jsjdj sjsj`

**Comment by patrickgold** [comment]
> Did something change inside the settings? No text I write seems to get spell-checked anymore.

Nope, nothing has really changed at all. After your comment I went on investigating this behavior and found out the following:

- The GitHub editor is hugely inconsistent with what text is requested to be spell-checked. I played around quite some time and found out that Gboard's spell checker, beta05 (original FlorisBoard spell checker) and debug all behave the same. Very very rarely the GitHub app requests to check the whole text at all, mostly only the last 2 lines up until the cursor are requested (for performance reasons maybe?). Sometimes the spell checker does not get requested at all. Very very strange. But as Gboard behaves as weird too I suspect the bug within GitHub's app.
- I then tried a more stable app, Gmail and again Gboard and FlorisBoard behave the same, only that Gmail always requests all the text to be spell checked. The only difference was that Gboard was blazingly fast while FlorisBoard took 4-5 sec to check 2 paragraphs of lorem ipsum. I have to improve session-persistent caching a bit it seems.

Based on that observation can you check in your email app how spell check behaves there?

**Comment by Glitchy-Tozier** [comment]
> Based on that observation can you check in your email app how spell check behaves there?

In other apps the text seems to fully get checked.

___

Another issue: I feel like switching languages via that globe-button on the left of the space-bar  still doesn't update the spellcheck-language, even after typing some extra words.

Wasn't this is supposed to be implemented or did I misread some changelog?

**Comment by patrickgold** [comment]
> Another issue: I feel like switching languages via that globe-button on the left of the space-bar still doesn't update the spellcheck-language, even after typing some extra words.
Wasn't this is supposed to be implemented in the last beta or did I misunderstand some changelog?

Nope, that's included in PR #1172, the active branch I am currently working on. It will be included in beta10 tomorrow.

**Comment by Glitchy-Tozier** [comment]
> Nope, that's included in PR #1172, the active branch I am currently working on. It will be included in beta10 tomorrow.

Ah, never mind, then! 🙈
